services:
  - type: web
    name: lms-bot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT --timeout 300 --workers 2 --threads 2 --max-requests 100 --max-requests-jitter 50
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ALLOWED_ORIGINS
        value: "https://lmsbot-frontend.vercel.app,http://localhost:3000" 